name: Bump build numbers & update version name
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Updated app version name"
        required: true

jobs:
  bump-version-and-open-pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Update version in package.json and package-lock.json
        run: npm version --no-git-tag-version ${{ inputs.versionName }}

      - name: Extract and increment existing android build number
        id: get-android-build-number
        run: |
          # Get existing Android version code from build.gradle
          version_code_android=$(grep "versionCode" android/app/build.gradle | awk '{print $2}' | tr -d '\n')

          # Increment existing Android version code by 1
          version_code_android=$((version_code_android + 1))

          # Set env var for later use
          # echo "VERSION_CODE_ANDROID: $version_code_android"
          # echo "VERSION_CODE_ANDROID=$version_code_android" >> $GITHUB_ENV
          echo "versionCodeAndroid=$version_code_android" >> $GITHUB_OUTPUT

      - name: Set incremented Android build number
        run: sed -i '' 's/versionCode [0-9]*/versionCode ${{ steps.get-android-build-number.outputs.versionCodeAndroid }}/g' android/app/build.gradle

      - name: Update version name for Android
        run: sed -i '' "s/versionName \"[^\"]*\"/versionName \"${{ inputs.versionName }}\"/g" android/app/build.gradle

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Increment iOS build number
        run: bundle exec fastlane ios bump

      - name: Update version name for iOS
        run: bundle exec fastlane ios set_version_number version:${{ inputs.versionName }}

      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/config/changelog-config.json"
          outputFile: fastlane/metadata/android/en-US/changelogs/${{ steps.get-android-build-number.outputs.versionCodeAndroid }}.txt
          toTag: "HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_W_WORKFLOW_TRIGGER }}
          commit-message: "Incrementing version to ${{ inputs.versionName }}, bumping iOS and Android build numbers"
          branch: bump/v${{ inputs.versionName }}
          title: "App Version Updated to ${{ inputs.versionName }}"
          body: "App version name updated to ${{ inputs.versionName }} and build numbers incremented"
          base: "main"
          labels: "bump version"
