# Workflow based on this article https://www.paleblueapps.com/rockandnull/github-actions-android-version/
name: Bump version code & update version name
on:
  push:
    branches:
      - "bump/v*.*.*"
  workflow_dispatch:
    inputs:
      version_name:
        description: "App version name"
        type: string
jobs:
  bump-version-and-open-pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version name
        id: versionNameStep
        run: |
          VERSION_NAME=${{ github.event.inputs.version_name }}
          version_name=${GITHUB_REF#refs/heads/bump/v}

          echo "version_output=${VERSION_NAME:-$version_name}" >> "$GITHUB_OUTPUT"

      - name: Set version name
        run: |
          version="${{ steps.versionNameStep.outputs.version_output }}"
          echo "VERSION_NAME: $version"
          echo "VERSION_NAME=${{ steps.versionNameStep.outputs.version_output }}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Update version in package.json and package-lock.json
        run: npm version --no-git-tag-version ${{ env.VERSION_NAME }}

      - name: Extract existing android version code
        run: |
          # Get existing Android version code from build.gradle
          version_code_android=$(grep "versionCode" android/app/build.gradle | awk '{print $2}' | tr -d '\n')

          # Increment existing Android version code by 1
          version_code_android=$((version_code_android + 1))

          # Set env var for later use
          # echo "VERSION_CODE_ANDROID: $version_code_android"
          echo "VERSION_CODE_ANDROID=$version_code_android" >> $GITHUB_ENV

      - name: Increment Android build number
        run: sed -i '' 's/versionCode [0-9]*/versionCode ${{ env.VERSION_CODE_ANDROID }}/g' android/app/build.gradle

      - name: Update version for Android
        run: sed -i '' "s/versionName \"[^\"]*\"/versionName \"${{ env.VERSION_NAME }}\"/g" android/app/build.gradle

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Increment iOS build number
        run: bundle exec fastlane ios bump

      - name: Update version name for iOS
        run: bundle exec fastlane ios set_version_number

      - name: Commit and push changes if workflow_dispatch
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name == 'workflow_dispatch'
        with:
          commit_message: "Updating version to ${{ env.VERSION_NAME }} and incrementing build numbers"
          create_branch: true
          branch: "bump/v${{ env.VERSION_NAME }}"

      - name: Checkout created branch if workflow_dispatch
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: "bump/v${{ env.VERSION_NAME }}"

      - name: Commit and push changes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updating version to ${{ env.VERSION_NAME }} and incrementing build numbers"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_W_WORKFLOW_TRIGGER }}
          commit-message: "UPDATE APP VERSION: Incrementing version to ${{ env.VERSION_NAME }}, bumping iOS and Android build numbers"
          branch: "${{ github.ref }}"
          title: "Bump App to Version ${{ env.VERSION_NAME }}"
          body: "App version name updated to ${{ env.VERSION_NAME }} and build numbers incremented"
          base: "main"
