name: Tag and Prerelease
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # TODO: this trigger is temporary, used for testing
  workflow_dispatch:
    inputs:
      version_name:
        description: "App version name"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    # only runs if a bump app version PR is merged
    if: ${{ (startsWith(github.event.pull_request.title, 'Bump App')) && (github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      # - name: Build
      #   run: npm run build
      - name: Get tag
        id: get_tag
        run: |
          git branch --show-current
          git pull
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT
      - name: Tag the commit
        run: |
          next_version=${{ steps.get_tag.outputs.version }}
          git tag -a "$next_version" -m "Version $next_version"
          git push --follow-tags
      # TODO: remove --draft flag when ready
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" --generate-notes --prerelease
