name: Tag and Prerelease
on: workflow_dispatch

env:
  USERS_ALLOWED_TO_TRIGGER: '["salemlf"]'
jobs:
  prerelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should only be triggered on the main branch"
          exit 1

      - name: Fail if user is not in allowed list
        if: (!contains(fromJson(env.USERS_ALLOWED_TO_TRIGGER), github.actor))
        run: |
          echo "User is not in allowed list for triggering this workflow"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current version
        id: getAppVersion
        run: |
          echo "version=v$(cat package.json | grep \"version\" | cut -d'"' -f 4)" >> $GITHUB_OUTPUT

      - name: Set git info and tag the commit
        run: |
          git config --global user.email "salemlfenn@gmail.com"
          git config --global user.name "Salem Fenn"

          updated_tag=${{ steps.getAppVersion.outputs.version }}
          git tag -a "$updated_tag" -m "Version $updated_tag"
          git push origin --tags

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.getAppVersion.outputs.version }}
        run: |
          gh release create "$tag" --generate-notes --prerelease
